//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosWInApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesBill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesBill()
        {
            this.SalesBillProducts = new HashSet<SalesBillProduct>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string notes { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<int> userId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesBillProduct> SalesBillProducts { get; set; }
    }
}
