//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosWInApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesBillProduct
    {
        public int salesBillId { get; set; }
        public int productId { get; set; }
        public Nullable<decimal> productPrice { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual SalesBill SalesBill { get; set; }
    }
}
